### PR TITLE
force javascript calculate numbers

### PR DESCRIPTION
**Pull request by Jaehyuk-Lee**
someone got problem with this code, (maybe this problem is for everyone)
`this.options.BigBuffIconWidth + 2` was not calculating numbers. was attaching those two as strings.
I think this will fix this problem.

### CODE REVIEW

**Comment by quisquous** [comment]
Hmm! Do you know how this happened? Did somebody type letters into the config box, or did they set a file in `cactbot/user/`?

Mostly I'm wondering if it would be better to just do a parseInt/parseFloat during the options setting on everything vs this one variable.

**Comment by Jaehyuk-Lee** [comment]
http://www.inven.co.kr/board/ff14/4953/3298
I don't know how this happened but post writer said string attachment was problem.

**Comment by quisquous** [comment]
Thanks for the link, that's really helpful context. Sorry for writing my own patch here and not taking this pull request, but this seemed like a more general problem.  By catching it upstream, I think this will fix all issues, like BigBuffIconHeight as well as BigBuffIconWidth, and all integer/float values.

**Comment by Jaehyuk-Lee** [comment]
okay, i understand

**Pull request closed without merging**
