### PR TITLE
resources: support position fields for startsUsing

### PR DESCRIPTION
**Pull request by quisquous**

### CODE REVIEW

**Review by JLGarber — APPROVED** [review]

**Comment by valarnin** [comment]
Just to verify, these are source position/heading, not target, correct?

**Comment by MaikoTan** [comment]
> Just to verify, these are source position/heading, not target, correct?

https://github.com/ravahn/FFXIV_ACT_Plugin/releases/tag/2.2.0.6

Ravahn said this is "caster's", so yes.

**Review by panicstevenson — APPROVED** [review]
Should this be updated in the [LogGuide](https://github.com/quisquous/cactbot/blob/main/docs/LogGuide.md)?

**Comment by quisquous** [comment]
> Should this be updated in the [LogGuide](https://github.com/quisquous/cactbot/blob/main/docs/LogGuide.md)?

Nobody's updated the log guide yet to list out network log lines, so ... yes but not yet so no?

**Pull request merged**
