### PR TITLE
raidboss: DSRU Adjust timing of baited protean move call

### PR DESCRIPTION
**Pull request by valarnin**
As was discussed previously, adjust the timing of the move call for the baited protean to be closer to where it actually snapshots.

### CODE REVIEW

**Comment by quisquous** [comment]
I tried this with startsUsing + 3 (the actual cast time between 14/15 lines, although I'm sure it is 2.70 in the log line itself as it always is), and it felt the same as using ability to me.

In general, an implicit rule I've tried to follow is "if cactbot tells you to do something, then you should be able to do that thing *right now*", e.g. knockback or move left or move away or the Nidhogg "in/out" follow-up call after the first "out/in" goes off.  

However, my worry here with the baited protean call is that I think it would be worse if cactbot called it out early and folks moved ahead of the castbar finishing as soon as the text appeared, and baited their proteans off to the side where they will kill people.  And, I'm not sure how to arbitrarily move this backwards in time in a way that will work for everybody (or will work in the future if somebody makes processing logs/getting stuff on screen faster).

Personally, I think this is a case where the "move" is a last minute (but safe) reminder to move, and will still help some people.  Other "safe" alternatives could be "bait proteans" on the cast (and then people can look at their cast bar to time it better).

**Comment by Legends0** [comment]
I even think the move call out as it is now is early enough to get another gcd cast in.

**Comment by valarnin** [comment]
Relevant lines below.

First line is the startsUsing. (this PR targets startsUsing + 2.20s, functionally)
Second line is the ability. (current main branch target, startsUsing + 2.984s)
Third through eleventh line (grouped) are the startsUsing lines for the actual proteans. If the player moves at this point, it's too late, they're going to be server ticked in the protean. (startsUsing + 3.072s)
Twelfth through nineteenth lines included for posterity, the corresponding ability lines.

With a 90ms ping, I move even before this modified trigger fires and the protean is still snapshot'd in the right spot.

With the current main branch code, there's an 88ms window to move between when the trigger fires and when it's too late.
With this PR's trigger, there's an 872ms window to move.

```
20|2022-05-05T23:01:48.7200000-04:00|4002E21A|King Thordan|63C8|Ascalon's Mercy Concealed|4002E21A|King Thordan|2.70|99.93|101.09|0.00|3.13|c37054d7e5c0888d

21|2022-05-05T23:01:51.7040000-04:00|4002E21A|King Thordan|63C8|Ascalon's Mercy Concealed|4002E21A|King Thordan|1B|63C88000|0|0|0|0|0|0|0|0|0|0|0|0|0|0|6717463|7439000|10000|10000|||99.93|101.09|0.00|3.13|6717463|7439000|10000|10000|||99.93|101.09|0.00|3.13|00016319|0|1|da13d7a4773608ce

20|2022-05-05T23:01:51.7920000-04:00|4002E22D|King Thordan|63C9|Ascalon's Mercy Concealed|4002E22D|King Thordan|1.20|99.95|101.11|0.00|-0.29|ba3326b4fd745d41
20|2022-05-05T23:01:51.7920000-04:00|4002E22C|King Thordan|63C9|Ascalon's Mercy Concealed|4002E22C|King Thordan|1.20|99.95|101.11|0.00|3.06|51db50ea0e3c129a
20|2022-05-05T23:01:51.7920000-04:00|4002E22F|King Thordan|63C9|Ascalon's Mercy Concealed|4002E22F|King Thordan|1.20|99.95|101.11|0.00|0.03|8579ac51961d1239
20|2022-05-05T23:01:51.7920000-04:00|4002E22E|King Thordan|63C9|Ascalon's Mercy Concealed|4002E22E|King Thordan|1.20|99.95|101.11|0.00|0.10|78dc641caa5d14e1
20|2022-05-05T23:01:51.7920000-04:00|4002E231|King Thordan|63C9|Ascalon's Mercy Concealed|4002E231|King Thordan|1.20|99.95|101.11|0.00|0.00|b103ac92e1700aaa
20|2022-05-05T23:01:51.7920000-04:00|4002E230|King Thordan|63C9|Ascalon's Mercy Concealed|4002E230|King Thordan|1.20|99.95|101.11|0.00|0.10|613ad5e21ef0515f
20|2022-05-05T23:01:51.7920000-04:00|4002E233|King Thordan|63C9|Ascalon's Mercy Concealed|4002E233|King Thordan|1.20|99.95|101.11|0.00|0.01|37f0748c948ab0d0
20|2022-05-05T23:01:51.7920000-04:00|4002E232|King Thordan|63C9|Ascalon's Mercy Concealed|4002E232|King Thordan|1.20|99.95|101.11|0.00|0.04|edf6c99ab5c82004

21|2022-05-05T23:01:53.2600000-04:00|4002E22D|King Thordan|63C9|Ascalon's Mercy Concealed|E0000000||0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|||||||||||44|44|0|10000|||99.95|101.11|0.00|-0.29|00016329|0|0|75f64de1f53112af
21|2022-05-05T23:01:53.2600000-04:00|4002E22C|King Thordan|63C9|Ascalon's Mercy Concealed|E0000000||0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|||||||||||44|44|0|10000|||99.95|101.11|0.00|3.06|0001632A|0|0|2a6c8436a25bec9c
21|2022-05-05T23:01:53.2600000-04:00|4002E22F|King Thordan|63C9|Ascalon's Mercy Concealed|E0000000||0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|||||||||||44|44|0|10000|||99.95|101.11|0.00|0.03|0001632B|0|0|069f72ed2804279b
21|2022-05-05T23:01:53.2600000-04:00|4002E22E|King Thordan|63C9|Ascalon's Mercy Concealed|E0000000||0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|||||||||||44|44|0|10000|||99.95|101.11|0.00|0.10|0001632C|0|0|a1fc37df47cdc373
21|2022-05-05T23:01:53.2600000-04:00|4002E231|King Thordan|63C9|Ascalon's Mercy Concealed|E0000000||0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|||||||||||44|44|0|10000|||99.95|101.11|0.00|0.00|0001632D|0|0|1a4016a1a0da1e9f
21|2022-05-05T23:01:53.2600000-04:00|4002E230|King Thordan|63C9|Ascalon's Mercy Concealed|E0000000||0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|||||||||||44|44|0|10000|||99.95|101.11|0.00|0.10|0001632E|0|0|28802c97702d0657
21|2022-05-05T23:01:53.2600000-04:00|4002E233|King Thordan|63C9|Ascalon's Mercy Concealed|E0000000||0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|||||||||||44|44|0|10000|||99.95|101.11|0.00|0.01|0001632F|0|0|314a6cfe62b89e58
21|2022-05-05T23:01:53.2600000-04:00|4002E232|King Thordan|63C9|Ascalon's Mercy Concealed|E0000000||0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|||||||||||44|44|0|10000|||99.95|101.11|0.00|0.04|00016330|0|0|587a912f202ad96c
```

**Comment by quisquous** [comment]
Thanks for the timings.  It does sure seem like the baited positions have to happen prior to the 63C8 ability if the 63C9 starts using have locked in positions.  Hopefully my concern above about telling people to move prior to when they can move makes sense, though.  Sorry for the doubt, but I think I want to give this a try myself a little (or I'd take video with the timeline debug time on) and then will merge it.

> First line is the startsUsing. (this PR targets startsUsing + 2.20s, functionally)

Maybe I'm misunderstanding, but the castTime in the cast line is 2.7 (while the actual time is 3 between 20/21 lines).  You are doing 1.7 (2.7 - 1 = 1.7)?

**Comment by valarnin** [comment]
> Maybe I'm misunderstanding, but the castTime in the cast line is 2.7 (while the actual time is 3 between 20/21 lines). You are doing 1.7 (2.7 - 1 = 1.7)?

Sorry, this was supposed to be -0.5, guessing vscode didn't save that change before actually staging the file. vscode+WSL has some quirks. I'll get this corrected shortly.

I was playing around with -1 as well, but that was too close to the actual snapshot for the bait that it was catching the 50ms-latency players in my group.

**Comment by quisquous** [comment]
I think 0.5 is still too early: https://clips.twitch.tv/FunnyDreamyLorisPastaThat-E8Qm1w8cpclnMxl_

The cast time is already 0.3 shorter than the ability, so this is 0.8 short total.  What about 0.4 instead of 0.5?

**Comment by quisquous** [comment]
Yeah, that sounds fine to me too.  As I said before, I think it's really bad if something like this calls out too early and kills people and so it's something I'd prefer to avoid as much as possible.

**Pull request merged**
