### PR TITLE
raidemulator: Convert CombatantTracker and subclasses to typescript

### PR DESCRIPTION
**Pull request by valarnin**
Converting CombatantTracker and related dependencies to typescript.

I had to touch a lot of the LineEvent classes to let pulling combatant info work after converting to concrete types, which caused this PR to be bigger than I would have liked.

There's a fair amount of code here that'll probably need updated once someone with some more deep knowledge of typescript reviews, there's a lot of `... as ...` casting in Combatant.ts for example due to bounds checks that tsc doesn't seem to understand.

### CODE REVIEW

**Comment by quisquous** [comment]
There are a lot of files here.  Are there smaller dependencies you can pick off first?

**Comment by valarnin** [comment]
This could be split into two PRs such that:

1. LineEvent interfaces are added and those classes updated, with about half of the updates to CombatantTracker (CombatantTracker stays as javascript)
  - ~300 additions, ~200 deletions, 13 files changed
2. Typescript conversion of CombatantTracker and subclasses
  - ~300 addtions, ~275 deletions, 4 files changed

raidemulator would likely be broken between those two PRs getting merged, as well, depending on how much I can get CombatantTracker's changes in PR 1 to function.

If you don't mind raidemulator being broken for a while, I can break this down into as many small PRs as you'd like. The whole raidemulator typescript conversion is starting to feel like it might benefit from being done on a branch?

**Comment by quisquous** [comment]
```
ui/raidboss/emulator/data/CombatantJobSearch.ts
ui/raidboss/emulator/data/CombatantState.ts
ui/raidboss/emulator/data/network_log_converter/LineEvent.ts
  depend on nothing

ui/raidboss/emulator/data/Combatant.ts
  depends on CombatantState
 
ui/raidboss/emulator/data/network_log_converter/LineEvent0x03.ts
ui/raidboss/emulator/data/network_log_converter/LineEvent0x14.ts
ui/raidboss/emulator/data/network_log_converter/LineEvent0x15.ts
ui/raidboss/emulator/data/network_log_converter/LineEvent0x17.ts
ui/raidboss/emulator/data/network_log_converter/LineEvent0x18.ts
ui/raidboss/emulator/data/network_log_converter/LineEvent0x1A.ts
ui/raidboss/emulator/data/network_log_converter/LineEvent0x1B.ts
ui/raidboss/emulator/data/network_log_converter/LineEvent0x22.ts
ui/raidboss/emulator/data/network_log_converter/LineEvent0x25.ts
ui/raidboss/emulator/data/network_log_converter/LineEvent0x26.ts
ui/raidboss/emulator/data/network_log_converter/LineEvent0x27.ts
  depends on LineEvent
  
ui/raidboss/emulator/data/CombatantTracker.ts
  depends on Combatant
  depends on CombatantState
  depends on CombatantJobSearch
  depends on LineEvent
```

How about this series of PRs?
* CombatantJobSearch
* CombatantState
* Combatant
* LineEvent*
* CombtantTracker

**Comment by valarnin** [comment]
- `CombatantJobSearch.getJob`'s signature changed from `abilityID: string` to `abilityID: number`, so `CombatantTracker`'s call would need to be updated, or the signature change would have to happen further down in another PR
- `CombatantState.partialClone`'s `props` argument was changed from allowing `string | number` props to requiring `number` props, so `Combatant` would need to be updated to reflect that change or it would have to be done further down in another PR
- As stated in my previous comment, `LineEvent*` classes were normalized to follow the interface specs, so `CombatantTracker` would have to be updated to reflect this change, there's no splitting this into another PR further down

As such, the series of PRs you outlined would be:

- `CombatantJobSearch => ts` + a single-line adjustment to `CombatantTracker`
- `CombatantState => ts` + roughly half of the changes to `Combatant`
- `Combatant => ts` + roughly 2/3ds of the changes to `CombatantTracker`
- `LineEvent*` changes + changing about 1/3rd of the code that was previously adjusted in `CombatantTracker` to reference the normalized properties
- `CombatantTracker => ts`

There's just not a clean division of code for these classes because they're all pretty tightly coupled. Part of the reason of changing `LineEvent*` classes is to reduce some of that tight coupling.

**Comment by quisquous** [comment]
What you outline looks good, with maybe combining CombatantState + CombatantTracker.  I think it's hard to separate these things out afterwards rather than make smaller changes up front.

**Comment by quisquous** [comment]
Deleted previous comment as the suggestion didn't make sense, sorry.

What about then:

* CombatantJobSearch => ts + a single-line adjustment to CombatantTracker
* LineEvent* changes + changing about 1/3rd of the code that was previously adjusted in CombatantTracker to reference the normalized properties
* CombatantState + Combatant + CombatantTracker together if they're really all that entwined

It's just hard to review a 20 file change where there's logic and typescript and a bunch of changes, and it's even harder to try to separate it out afterwards.  I think it'd be easier all around if there were just smaller patches up front, or fewer logic changes when there are also TypeScript conversions?

**Comment by valarnin** [comment]
Closing this PR in favor of other PRs that were split off from this.

**Pull request closed without merging**
