### PR TITLE
raidemulator: Convert NetworkLogConverter and direct dependencies to typescript

### PR DESCRIPTION
**Pull request by valarnin**
This PR is part one of converting RaidEmulator to typescript.

A quick note that because `EmulatorCommon` isn't included as part of this PR, the calls to `EmulatorCommon.properCase` are being recast as `... as string`.

There's some ugly code in `NetworkLogConverter.convertLines` which I couldn't see any way of handling better while avoiding memory issues. If you have any better suggestions which don't involve leaving the old values around in the function scope, I can clean it up further in another PR. As it exists in this PR, it matches the javascript version's logic.

### CODE REVIEW

**Comment by quisquous** [comment]
I think when I said "simple/no changes" and "some files" I didn't mean +1,356 −781 and 51 files changed :eyes:.  I was thinking more on the order of #2829 or #2795.

Can I propose starting with `network_log_converter/LineEvent0x*.js` on its own plus pasting a diff like https://github.com/quisquous/cactbot/pull/2841#issuecomment-832845693 does so I can see what's changed more directly? I think that would make this much more manageable for me and anybody else looking at this.

**Comment by valarnin** [comment]
So, GitHub detected the rename for some of the files, but not others, somehow?

Either way, dropping the non-LineEvent files would only really drop the line change count by ~200, and the extra files are all pretty tightly coupled to the LineEvent files.

I'm not sure I could offer a compilable/valid version of the non-LineEvent files while having the LineEvent files converted.

For reference:
```
$ wc -l ui/raidboss/emulator/data/network_log_converter/LineEvent*
   62 ui/raidboss/emulator/data/network_log_converter/LineEvent.ts
   57 ui/raidboss/emulator/data/network_log_converter/LineEvent0x00.ts
   35 ui/raidboss/emulator/data/network_log_converter/LineEvent0x01.ts
   28 ui/raidboss/emulator/data/network_log_converter/LineEvent0x02.ts
  106 ui/raidboss/emulator/data/network_log_converter/LineEvent0x03.ts
   24 ui/raidboss/emulator/data/network_log_converter/LineEvent0x04.ts
   40 ui/raidboss/emulator/data/network_log_converter/LineEvent0x0C.ts
   72 ui/raidboss/emulator/data/network_log_converter/LineEvent0x14.ts
  142 ui/raidboss/emulator/data/network_log_converter/LineEvent0x15.ts
   14 ui/raidboss/emulator/data/network_log_converter/LineEvent0x16.ts
   33 ui/raidboss/emulator/data/network_log_converter/LineEvent0x17.ts
  111 ui/raidboss/emulator/data/network_log_converter/LineEvent0x18.ts
   68 ui/raidboss/emulator/data/network_log_converter/LineEvent0x19.ts
   99 ui/raidboss/emulator/data/network_log_converter/LineEvent0x1A.ts
   31 ui/raidboss/emulator/data/network_log_converter/LineEvent0x1B.ts
   29 ui/raidboss/emulator/data/network_log_converter/LineEvent0x1C.ts
   24 ui/raidboss/emulator/data/network_log_converter/LineEvent0x1D.ts
   34 ui/raidboss/emulator/data/network_log_converter/LineEvent0x1E.ts
   71 ui/raidboss/emulator/data/network_log_converter/LineEvent0x1F.ts
   35 ui/raidboss/emulator/data/network_log_converter/LineEvent0x22.ts
   38 ui/raidboss/emulator/data/network_log_converter/LineEvent0x23.ts
   29 ui/raidboss/emulator/data/network_log_converter/LineEvent0x24.ts
   59 ui/raidboss/emulator/data/network_log_converter/LineEvent0x25.ts
   72 ui/raidboss/emulator/data/network_log_converter/LineEvent0x26.ts
   54 ui/raidboss/emulator/data/network_log_converter/LineEvent0x27.ts
 1367 total
```

**Comment by valarnin** [comment]
As a follow up, a lot of the added lines were due to having to properly type the `parts` argument to the constructors of the LineEvent classes.

For an example on one of the files that the rename was detected properly, check `LineEvent0x01.ts`.

**Comment by quisquous** [comment]
Proposal:

PR 1:
* ui/raidboss/emulator/data/network_log_converter/LineEvent.ts
* ui/raidboss/emulator/data/network_log_converter/LogRepository.ts
* ui/raidboss/emulator/EmulatorCommon.ts

PR 2:
* ui/raidboss/emulator/data/network_log_converter/LineEvent0x*.ts

PR 3:
* ui/raidboss/emulator/data/network_log_converter/ParseLine.ts

PR 4:
* ui/raidboss/emulator/data/NetworkLogConverter.ts
* ui/raidboss/emulator/data/NetworkLogConverterWorker.js

**Comment by valarnin** [comment]
Closed in favor of #2875

**Pull request closed without merging**
