### PR TITLE
util: disable lint on coverage report

### PR DESCRIPTION
**Pull request by quisquous**
Coverage report went from 2m to 20m when adding dprint.

An initial attempt to just add an "eslint-disable dprint/dprint"
line to the coverage report made it take 60m to complete (!!!).

For simplicity, just disable lint on this generated file.

### CODE REVIEW

**Comment by valarnin** [comment]
I couldn't get timings for dprint to see what was killing its performance, but running once without dprint and then a second time with dprint, timings are much more sane, time to lint is 5 seconds:

```
linting... 1628102663188
done eslint... +4842; 1628102668030
done dprint... +106; 1628102668136
```

Here's the changes without the debug lines:

```diff
diff --git a/util/gen_coverage_report.js b/util/gen_coverage_report.js
index 1115eabc..48b1213d 100644
--- a/util/gen_coverage_report.js
+++ b/util/gen_coverage_report.js
@@ -231,13 +231,28 @@ const writeCoverageReport = async (outputFileName, coverage, totals) => {
     `export const coverage = ${JSON.stringify(coverage, undefined, 2)};\n\n` +
     `export const coverageTotals = ${JSON.stringify(totals, undefined, 2)};\n`;

-  const linter = new eslint.ESLint({ fix: true });
-  const results = await linter.lintText(str, { filePath: outputFileName });
+  const dprintLinter = new eslint.ESLint({ fix: true });
+
+  // Get the default config for output file, remove dprint
+  const config = await dprintLinter.calculateConfigForFile(outputFileName);
+  config.plugins = config.plugins.filter((p) => p !== 'dprint');
+  delete config.rules['dprint/dprint'];
+
+  const linter = new eslint.ESLint({ fix: true, useEslintrc: false, baseConfig: config });
+  const eslintResults = await linter.lintText(str, { filePath: outputFileName });
+
+  const eslintLintResult = eslintResults[0];
+  if (eslintLintResult.errorCount > 0 || eslintLintResult.warningCount > 0) {
+    console.error('Lint (eslint) ran with errors, aborting.');
+    process.exit(2);
+  }
+
+  const results = await linter.lintText(eslintLintResult.output, { filePath: outputFileName });

   // There's only one result from lintText, as per documentation.
   const lintResult = results[0];
   if (lintResult.errorCount > 0 || lintResult.warningCount > 0) {
-    console.error('Lint ran with errors, aborting.');
+    console.error('Lint (eslint+dprint) ran with errors, aborting.');
     process.exit(2);
   }

@@ -249,7 +264,7 @@ const writeCoverageReport = async (outputFileName, coverage, totals) => {
     process.exit(-1);
   });

-  writer.write(lintResult.output);
+  writer.write(eslintLintResult.output);
 };

 (async () => {
```

**Comment by quisquous** [comment]
Oh, interesting! I tried disabling dprint with a comment, but somehow that didn't quite get the same time savings.  This is a really nice suggestion, thanks!

**Comment by quisquous** [comment]
```diff
-  writer.write(lintResult.output);
+  writer.write(eslintLintResult.output);
```

Hmm, shouldn't this still be `lintResult.output`, since `lintResult` is the result of the second run of lint? (But if I do that, then the output is undefined for some reason?)

**Comment by valarnin** [comment]
When I went through and cleaned up all the debug output and fixed my original horrible variable names, I made a couple mistakes, sorry. This should be the correct patch, I hope?

The concept is create default rules linter (`dprintLinter`), get rules from that, create `linter` without dprint enabled, run original through `linter`, run output of `linter` through `dprintLinter`, write output of `dprintLinter` to file.

```diff
diff --git a/util/gen_coverage_report.js b/util/gen_coverage_report.js
index 1115eabc..021c79bc 100644
--- a/util/gen_coverage_report.js
+++ b/util/gen_coverage_report.js
@@ -231,13 +231,31 @@ const writeCoverageReport = async (outputFileName, coverage, totals) => {
     `export const coverage = ${JSON.stringify(coverage, undefined, 2)};\n\n` +
     `export const coverageTotals = ${JSON.stringify(totals, undefined, 2)};\n`;

-  const linter = new eslint.ESLint({ fix: true });
-  const results = await linter.lintText(str, { filePath: outputFileName });
+  const dprintLinter = new eslint.ESLint({ fix: true });
+
+  // Get the default config for output file, remove dprint
+  const config = await dprintLinter.calculateConfigForFile(outputFileName);
+  config.plugins = config.plugins.filter((p) => p !== 'dprint');
+  delete config.rules['dprint/dprint'];
+
+  const linter = new eslint.ESLint({ fix: true, useEslintrc: false, baseConfig: config });
+  const eslintResults = await linter.lintText(str, { filePath: outputFileName });
+
+  const eslintLintResult = eslintResults[0];
+  if (eslintLintResult.errorCount > 0 || eslintLintResult.warningCount > 0) {
+    console.error('Lint (eslint) ran with errors, aborting.');
+    process.exit(2);
+  }
+
+  const results = await dprintLinter.lintText(
+    eslintLintResult.output,
+    { filePath: outputFileName },
+  );

   // There's only one result from lintText, as per documentation.
   const lintResult = results[0];
   if (lintResult.errorCount > 0 || lintResult.warningCount > 0) {
-    console.error('Lint ran with errors, aborting.');
+    console.error('Lint (eslint+dprint) ran with errors, aborting.');
     process.exit(2);
   }
```

**Comment by quisquous** [comment]
Yeah, that's approximately what I had tried, but pasting your change in ends up with an undefined `lintResult.output`, which I'm not sure I understand why.

**Comment by valarnin** [comment]
I've apparently messed something else up as well during the cleanup/removal of debug text, because I'm getting the same. Let me poke at it some more. `output` is undefined because dprint isn't enabled for some reason at that point, so there are no changes to the input string, so per documentation there's no output because there's no fixable messages.

**Comment by valarnin** [comment]
So apparently we're actually getting back the underlying config objects and not a copy. Modifying that config object also modifies it for any subsequent calls, even on other eslint objects.

There are two options to fix.

1. Store off the original values, restore them after we've run without dprint, we don't need a second eslint parent object:
```diff
diff --git a/util/gen_coverage_report.js b/util/gen_coverage_report.js
index 1115eabc..a1583a9e 100644
--- a/util/gen_coverage_report.js
+++ b/util/gen_coverage_report.js
@@ -231,13 +231,36 @@ const writeCoverageReport = async (outputFileName, coverage, totals) => {
     `export const coverage = ${JSON.stringify(coverage, undefined, 2)};\n\n` +
     `export const coverageTotals = ${JSON.stringify(totals, undefined, 2)};\n`;

-  const linter = new eslint.ESLint({ fix: true });
-  const results = await linter.lintText(str, { filePath: outputFileName });
+  const dprintLinter = new eslint.ESLint({ fix: true });
+
+  // Get the default config for output file, remove dprint
+  const config = await dprintLinter.calculateConfigForFile(outputFileName);
+  const origPlugins = [...config.plugins];
+  const origRule = config.rules['dprint/dprint'];
+  config.plugins = config.plugins.filter((p) => p !== 'dprint');
+  delete config.rules['dprint/dprint'];
+
+  const linter = new eslint.ESLint({ fix: true, useEslintrc: false, baseConfig: config });
+  const eslintResults = await linter.lintText(str, { filePath: outputFileName });
+
+  const eslintLintResult = eslintResults[0];
+  if (eslintLintResult.errorCount > 0 || eslintLintResult.warningCount > 0) {
+    console.error('Lint (eslint) ran with errors, aborting.');
+    process.exit(2);
+  }
+
+  config.plugins = origPlugins;
+  config.rules['dprint/dprint'] = origRule;
+
+  const results = await dprintLinter.lintText(
+    eslintLintResult.output,
+    { filePath: outputFileName },
+  );

   // There's only one result from lintText, as per documentation.
   const lintResult = results[0];
   if (lintResult.errorCount > 0 || lintResult.warningCount > 0) {
-    console.error('Lint ran with errors, aborting.');
+    console.error('Lint (eslint+dprint) ran with errors, aborting.');
     process.exit(2);
   }
```

2. Clone the options via JSON.stringify/JSON.parse, and modify the clone. This is what I originally did:

```diff
diff --git a/util/gen_coverage_report.js b/util/gen_coverage_report.js
index 1115eabc..b0581d84 100644
--- a/util/gen_coverage_report.js
+++ b/util/gen_coverage_report.js
@@ -231,13 +231,33 @@ const writeCoverageReport = async (outputFileName, coverage, totals) => {
     `export const coverage = ${JSON.stringify(coverage, undefined, 2)};\n\n` +
     `export const coverageTotals = ${JSON.stringify(totals, undefined, 2)};\n`;

-  const linter = new eslint.ESLint({ fix: true });
-  const results = await linter.lintText(str, { filePath: outputFileName });
+  const dprintLinter = new eslint.ESLint({ fix: true });
+
+  // Get the default config for output file, remove dprint
+  const config = JSON.parse(
+    JSON.stringify(await dprintLinter.calculateConfigForFile(outputFileName)),
+  );
+  config.plugins = config.plugins.filter((p) => p !== 'dprint');
+  delete config.rules['dprint/dprint'];
+
+  const linter = new eslint.ESLint({ fix: true, useEslintrc: false, baseConfig: config });
+  const eslintResults = await linter.lintText(str, { filePath: outputFileName });
+
+  const eslintLintResult = eslintResults[0];
+  if (eslintLintResult.errorCount > 0 || eslintLintResult.warningCount > 0) {
+    console.error('Lint (eslint) ran with errors, aborting.');
+    process.exit(2);
+  }
+
+  const results = await dprintLinter.lintText(
+    eslintLintResult.output,
+    { filePath: outputFileName },
+  );

   // There's only one result from lintText, as per documentation.
   const lintResult = results[0];
   if (lintResult.errorCount > 0 || lintResult.warningCount > 0) {
-    console.error('Lint ran with errors, aborting.');
+    console.error('Lint (eslint+dprint) ran with errors, aborting.');
     process.exit(2);
   }
```

I just verified that both of these options work and produce the full eslint+dprint'd file.

**Comment by quisquous** [comment]
Aha!  Thanks for figuring it out.

**Pull request merged**
