### PR TITLE
Raidboss: E3S

### PR DESCRIPTION
**Pull request by VanSlanzar**
Spelling correction fr

### CODE REVIEW

**Comment by quisquous** [comment]
Can you chat with @mooondark about what's best to do here? I don't want to change things one way and then have changes back.

**Comment by VanSlanzar** [comment]
sure, how ?  
I noticed my error between (zone and flaque) and I think (zone) is more appropriate. The rest is French grammar correction. I am very careful, so as not to bother you anymore. i verified all. Sorry.

**Comment by VanSlanzar** [comment]
I would not modify any more, it will remain [(area on the ground, zones au sol in french). I'm not too familiar with your grammar, but ours is particularly rich in words and punctuation. 
I am passionate, but I am very disturbed. Now that I'm used to it, I'll do my best to stop making multiple requests for the same file.
Sorry for the worries created.

**Comment by VanSlanzar** [comment]
Hello,

I noticed my error between (zone and flaque) and I think (zones au sol) is
more appropriate. The rest is French grammar correction. I am very careful,
so as not to bother you anymore. I verified all. Sorry.
I would not modify any more, it will remain [(area on the ground, zones au
sol in french). I reopened some Eden files where I made the error, so that
they could be corrected.
 I'm not too familiar with your grammar, but ours is particularly rich in
words and punctuation.
I did not contact https://github.com/mooondark because I am certain of
myself. But if you really want it I would.
I am passionate, but I am very disturbed. Now that I'm used to it, I'll do
my best to stop making multiple requests for the same file.
Sorry for the worries created.

Le ven. 20 mars 2020 à 00:02, Adrienne Walker <notifications@github.com> a
écrit :

**Comment by quisquous** [comment]
It was less about how sure you were, and more that there are now multiple people making changes to French translations.  I think I just want to make sure that you two agree on what these should look like.

**Comment by VanSlanzar** [comment]
yes it's true and I understand. I left a comment inviting moondark and leave me comments on my posts

**Pull request merged**
