### PR TITLE
add a trigger for TEA alpha phase

### PR DESCRIPTION
**Pull request by Trim21**
@MaikoTan help me to translate it.

I haven't tested it in-game, I haven't passed phase 3 yet. I'm not sure if it works fine.

Hoping someone could test it.

### CODE REVIEW

**Comment by quisquous** [comment]
Does `TEA Alpha Safe Spot` do you what you're trying to do already?

**Comment by MaikoTan** [comment]
I got no idea about what you're trying to do, can you explain it first?
And why does it return blank data by XIVAPI with the abilily id you've written?
https://xivapi.com/Action/18591?columns=Name,Name_de,Name_fr,Name_ja

**Comment by miaonima** [comment]
What mechanic is this? On which phase? Thanks.

**Comment by Trim21** [comment]
@miaonima alpha phase, safe location. Avoiding 3 Sacrament

**Comment by miaonima** [comment]
I think cactbot already has callouts for p4 alpha phase. Besides your enumeration, it says LEFT/RIGHT for safe spot, (and opposite direction if you have Defamation huge circle AOE). I am wondering if your proposal is the same as 'TEA Alpha Safe Spot' trigger. Please let me know your thoughts.

**Pull request closed without merging**
