### PR TITLE
util: Rework overlay API and overrides

### PR DESCRIPTION
**Pull request by quisquous**

### CODE REVIEW

**Comment by valarnin** [comment]
Thanks for this. I've been waylaid by IRL issues and didn't have the time required to properly test this change, so I'm glad you were able to get to it.

🧙

**Comment by quisquous** [comment]
> Thanks for this. I've been waylaid by IRL issues and didn't have the time required to properly test this change, so I'm glad you were able to get to it.

I ran an e6s log through the emulator and verified that `E6S Strike Spark` worked ok.  Is there anything else I should try?

**Comment by valarnin** [comment]
> I ran an e6s log through the emulator and verified that `E6S Strike Spark` worked ok. Is there anything else I should try?

Probably test the general test trigger for watchCombatants in Summerford Farms?

**Comment by quisquous** [comment]
> Probably test the general test trigger for watchCombatants in Summerford Farms?

That seems fine too.  Thanks for the suggestion!

**Pull request merged**
