### PR TITLE
add .vscode ignore

### PR DESCRIPTION
**Pull request by Jaehyuk-Lee**
There's new vscode extension.
I think we need `.vscode/` ignore.

### CODE REVIEW

**Comment by panicstevenson** [comment]
It's common practice to commit the `.vscode` folder and its contents, since they usually pertain to editor recommendations per repository. What's being added here that is causing issues?

**Comment by MaikoTan** [comment]
Well, I don't support this.

According to https://github.com/flutter/flutter/issues/15555 , it is not recommand to add IDE/OS-specific files in `.gitignore`.

In fact, you can set a global `.gitignore` via `git config --global core.excludeFiles /path/to/your/global/gitignore`.

**Comment by panicstevenson** [comment]
If this is for https://github.com/quisquous/cactbot/issues/1846#issuecomment-704966329 does it make sense to include this (although, I think there are other .txt files in that specific path)? This was something I had mentioned in that same thread: https://github.com/quisquous/cactbot/issues/1846#issuecomment-704655088

We can wait for quisquous for their guidance on VSCode, which they don't use. Although, I do know they have opinions on git.

**Comment by MaikoTan** [comment]
Hmmm...
If we want to include it into `gitignore`, this way is recommanded:

https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore

```
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
*.code-workspace

# Local History for Visual Studio Code
.history/
```


In my opinion, if this project recommands VSCode as primary developing environment, it is okay to upload those setting files to git.

**Comment by Jaehyuk-Lee** [comment]
Oh I thought this was usual
I did this somewhere else.
okay, closing this PR

**Comment by quisquous** [comment]
Are there user settings that end up in .vscode that shouldn't be committed and should be ignored? Sorry, as panic says above, I don't know much about it.

**Comment by Jaehyuk-Lee** [comment]
I don't know how most people does, but when I was in military service, we added `.vscode` to gitignore. I first met VS code in military and kept that habit until now.

(I mentioned military because I meant my experience is not usual thing since Korean military does not actively use habits of normal internet community or company.)

**Comment by MaikoTan** [comment]
Well, I don't support this because many people in my company using different IDE/editors.

My team mainly develops Java and VueJS applications, but everyone's habits are different. Some people like Idea, some people (such as me) like VSCode, and Vim and Emacs are said to be used. (And the operating system is even more diverse...)
Therefore, our company stipulates not to upload files related to the operating system and editor, unless the project specifies an editor as the main development tool.

Therefore, I think that if it is a personal project, it can naturally be handled at will, but as a community-participated project, these things still need to be considered?

Of course, the final choice lies with quisquous. I'm just talking about my thoughts, not trying to enforce it.

(Sorry I don't know how to describe it so I used Google Translation)

**Pull request closed without merging**
