### PR TITLE
i18n: add cn translate in p12s p1

### PR DESCRIPTION
**Pull request by lsl1225**

### CODE REVIEW

**Comment by quisquous** [comment]
Hi! Thanks for the translations. Could you add the missing commas that the lint check is complaining about? If you have `npm` install locally you should be able to run `npm run lintfix:dprint` and it will fix them automatically for you.

**Comment by lsl1225** [comment]
Thanks for the review! Should be correct now.

**Comment by quisquous** [comment]
Sorry, there's more lint errors!

**Comment by lsl1225** [comment]
> Sorry, there's more lint errors!

I'm looking into it, seems 'cn' should stay before 'ko'. Need some time to correct this. Thanks btw!

**Comment by quisquous** [comment]
You can run `npm run lint` and `npm run test` locally to test the same things that bots will do.  Also, sorry for the hassle but I merged in another translation patch that was ready to go, and so you will need to merge/rebase on top of main to resolve the conflicts as well.

**Comment by lsl1225** [comment]
Just opened a new pr #5583 to solve those issues, sorry for my mistakes!

**Pull request closed without merging**
