### PR TITLE
add timeline trigger for UWU

### PR DESCRIPTION
**Pull request by Trim21**

### CODE REVIEW

**Comment by Trim21** [comment]
Copy from titan-hm, maybe it's better to response tankCleave for all condition?

**Comment by quisquous** [comment]
> Copy from titan-hm, maybe it's better to response tankCleave for all condition?

Yeah, I think `tankCleave` in both cases seems good to me.

**Comment by Trim21** [comment]
there is another question I asked in last UWU trigger PR

> @quisquous I have a question about this. There is another groud effect ability(the laser in Ultimate Suppression, I don't know it's name in English) in UWU, and it's random, chose 1 from 3 choies(which can be distinguished by different ability id). It's not that visible like Land Weight and happened in the same time with another groud effect. Could I issue a pr for this?


> image

**Comment by quisquous** [comment]
> there is another question I asked in last UWU trigger PR
> 
> > @quisquous I have a question about this. There is another groud effect ability(the laser in Ultimate Suppression, I don't know it's name in English) in UWU, and it's random, chose 1 from 3 choies(which can be distinguished by different ability id). It's not that visible like Land Weight and happened in the same time with another groud effect. Could I issue a pr for this?
> 
> > image
> 
> And I can add it in this PR.

This is the "Aetherochemical Laser" trident coming from Ultima? Although I don't think that has three abilities? Can you give me the ability ids?

**Comment by Trim21** [comment]
@quisquous yes, I'll provide the trigger and raw log later.

**Pull request merged**
