### PR TITLE
raidboss: p3s timings for add phases

### PR DESCRIPTION
**Pull request by Legends0**
Based on some of my logs.

### CODE REVIEW

**Comment by Legends0** [comment]
Could probably smoosh the gaps so to include the timings after the enrages. It might be that even if we clear the adds, we have to still wait.

**Comment by Legends0** [comment]
A note regarding Experimental Fireplumes for the timeline. I would like some timing for the 66BE's fireplume as it's helpful to know when to run back in or out. The trigger for the get out is good. For the 66C0's Fireplumes, I find running out on the 2nd one, towards the second one to be the better timing.

**Comment by Legends0** [comment]
Brightened Fire takes some getting used to, I'd probably have it call out a swap for players +4 over the current Brightened Fire. There is some leeway for this movement. I find having to mentally count each number as it impacts.

**Comment by quisquous** [comment]
Before this gets merged, can you undo your changes to the german translations?

> Could probably smoosh the gaps so to include the timings after the enrages. It might be that even if we clear the adds early, we have to still wait.

I think it's fine to have jumps here.

> A note regarding Experimental Fireplumes for the timeline. I would like some timing for the 66BE's fireplume as it's helpful to know when to run back in or out. The trigger for the get out is good. For the 66C0's Fireplumes, I find running out on the 2nd one, towards the second one to be the better timing.

Agreed that the "out" needs a timeline line.  I left a comment about the timing but never added them in like they are in normal mode.

I am not sure what you're suggesting about the "rotate" version.  I run either towards the first or second explosion and either seem fine.

> Brightened Fire takes some getting used to, I'd probably have it call out a swap for players +4 over the current Brightened Fire. There is some leeway for this movement. I find having to mentally count each number as it impacts.

I am not sure what you're suggesting here either.  For prog we just stacked everybody (sorry healers) and had everybody not move.  I think "swap" is maybe strat specific.  I could see it calling out 1 2 3 4 5 6 7 8 with info text if you really wanted.

**Comment by quisquous** [comment]
Oh, I see what happened.  You removed the duplicate, but I didn't realize it was a duplicate.  Then I merged an actual removal, and now it's conflicting.  Sorry.

**Comment by Legends0** [comment]
> I am not sure what you're suggesting here either. For prog we just stacked everybody (sorry healers) and had everybody not move. I think "swap" is maybe strat specific. I could see it calling out 1 2 3 4 5 6 7 8 with info text if you really wanted.

My group was seeing 1hkos when we tried stacking the pairs, theoretically the debuff should fall off before the second hit but I guess there may have been some delay.

**Comment by quisquous** [comment]
> My group was seeing 1hkos when we tried stacking the pairs, theoretically the debuff should fall off before the second hit but I guess there may have been some delay.

Yeah, it should fall off just in time if you everybody only gets hit by the correct two.

**Pull request merged**
