### PR TITLE
raidboss: ASS/S simplify Rush of Might 1

### PR DESCRIPTION
**Pull request by quisquous**
This is subjective, but I find this style of instructions much easier to read and understand.

I asked a few people about this, and nobody is thinking about absolute north during this mechanic, and so "go east" when everybody is looking at the gladiators requires a lot more thinking.

I also understand that there is some ambiguity in "go left 1, right 2" (is it saying you need to go 2 the left or is the left one blinking 2 so you go 2 to the right, but hopefully the word "go" there makes it more obvious?)

### CODE REVIEW

**Comment by quisquous** [comment]
cc @Legends0 for wording opinions here; if other folks like the original better, I'm happy to just leave it as-is.  This worked for my brain a lot better.

**Comment by Legends0** [comment]
I don't quite understand how the text output covers all the cases because It's always saying go left, which means either west for the first rush set or east for the second. I thought this mechanic can force the safe spot to be on the right instead of left.

The only other concern I have is that the 2/3 or 3/2 case here where the place to stand is not different enough in phrasing to differentiate it from the other cases. Perhaps the original phrasing had this problem of where to stand as well.

**Comment by quisquous** [comment]
Yeah, the thought here is instead of trying to say precisely where to stand, it's to say how many notches to go down each line.  So "go 1 left 3 right" would mean on the line going front left to back right on the 3rd notch of that line.  In that case you'd be "on the right". You have to be able to form the intersection in your mind and form the intersection from that.

**Comment by xiashtra** [comment]
I think these are over-specific to the point of information overload.  I maintain my thoughts from the previous discussion on this mechanic: https://github.com/quisquous/cactbot/pull/5005#issuecomment-1295919986

The only information needed is which side is dashing farther and how far.  Instead of "left [x] right [y]" it could be "left [z]", etc.  The only pattern that might need a more unique call would be the 2/3 combinations, but again all you really need to know is which side is dashing farther and that it's a 2/3 combo.

**Comment by quisquous** [comment]
I think I disagree with "you only need to know which side is dashing further".  As you say, you have to know if it's a 2/3 or a 1/3.  And if you know that, then you know how far both sides are dashing, and not just the further one.  Just one side is not sufficient here.

Do you feel like "go right 1 left 3" is information overload as well?

**Comment by xiashtra** [comment]
> I think I disagree with "you only need to know which side is dashing further". As you say, you have to know if it's a 2/3 or a 1/3. And if you know that, then you know how far both sides are dashing, and not just the further one. Just one side is not sufficient here.
> 
> Do you feel like "go right 1 left 3" is information overload as well?

I think a call that includes both the words "left" and "right" simultaneously opens up the possibility of confusion in which side a player should move towards, when it could give you the same info with "right behind third line", "left behind second line" etc.

At the very least the call should order the side you need to move towards immediately after the word "go".  As it is currently, it can call "go right 3 left 1" when you should be moving towards the left.

**Comment by quisquous** [comment]
> At the very least the call should order the side you need to move towards immediately after the word "go". As it is currently, it can call "go right 3 left 1" when you should be moving towards the left.

Good idea.  This should be an easy fix to do.

**Comment by quisquous** [comment]
@xiashtra does this look like what you're asking for?

**Comment by quisquous** [comment]
Another option is that I could add all 6 possibilities and people could word them however they want.

**Comment by quisquous** [comment]
Ok, there's all options, and better wording for on the line.

**Comment by xiashtra** [comment]
> Another option is that I could add all 6 possibilities and people could word them however they want.

I think either of these works fine.  Having all 6 options allows for maximum user customization for those that want it.

**Comment by ssilve1989** [comment]
Just throwing my thoughts in here that what was there previously was perfectly fine. I find the new defaults confusing to know if its inside/outside. However looks like I'll just have to customize out of the defaults. 

In general, I find cardinal directions better to use over relative directions because it doesn't assume the direction anyone is facing. Sure, most parties will be looking south for the second rush, but you by no means have to, especially with Legacy movement.

**Comment by ibenny1011** [comment]
how do you customize back to the old one?

**Pull request merged**
