### PR TITLE
Make alertText idempotent in e9s triggers.

### PR DESCRIPTION
**Pull request by lyze**

### CODE REVIEW

**Comment by lyze** [comment]
Found this as part of #2822.

**Comment by quisquous** [comment]
I think "don't modify code in alertText" is a consideration if it makes code more readable, but I also am not sure it should be mandatory or worth changing triggers to support it at this point.

Personally, I think if this was something that we wanted to change, it'd make sense to wait until all triggers were typescript, and then we could pass a readonly data to text functions and verify that this was true.

**Comment by lyze** [comment]
> Personally, I think if this was something that we wanted to change, it'd make sense to wait until all triggers were typescript, and then we could pass a readonly data to text functions and verify that this was true.

Right, absolutely. This was the only obvious instance that I found. I felt this was a reasonable one-off cleanup to just send out regardless of whether we do anything in #2822.

**Comment by panicstevenson** [comment]
I feel like it's reasonable; however, there are (from my quick count) at least ~30 other cases of this, and my simple regular expression lookup didn't even find this case.

**Comment by quisquous** [comment]
Overall I'm not opposed to the code changes.  However, I don't think `RaidbossGuide` should be updated, mostly as stated before I don't think it's worth going through and changing old triggers to behave like this without some way to enforce it.  This is done and so it's here, but I don't think it's worth more PRs in this vein.

**Comment by lyze** [comment]
Got rid of the `RaidbossGuide` change.

**Pull request merged**
