### PR TITLE
raidboss: fix crystallize+aureole in 2nd EW extreme

### LINKED ISSUE #3817: Issue with Crystallize callouts near the end of Hydealyn Ex
Near the end of the fight the callouts are misleading as the order of actions change.

E.g. you `dodge Aureole > Water > Go In (red mark) ` but gets a callout for `In + Healer groups`

### PR DESCRIPTION
**Pull request by quisquous**
Fixes #3817.

### CODE REVIEW

**Comment by quisquous** [comment]
image

**Comment by nebularg** [comment]
This will cause the Crystallize before chakrams to carry through to the follow up Aureole, no? I haven't gone back in to Hydealyn for a few days, but seems like it could be a problem since there are no call outs for chakrams.

This bit
```
2016.7 "Anthelion" sync / 1[56]:[^:]*:Hydaelyn:6594:/
2026.9 "Mousa's Scorn" sync / 1[56]:[^:]*:Hydaelyn:65C0:/
2032.1 "--middle--" sync / 1[56]:[^:]*:Hydaelyn:6E7A:/
2038.7 "Parhelion" sync / 1[56]:[^:]*:Hydaelyn:65B0:/
2039.0 "Beacon 1" #sync / 1[56]:[^:]*:Parhelion:65B2:/
2040.6 "Beacon 2" #sync / 1[56]:[^:]*:Parhelion:65B2:/
2042.2 "Beacon 3" #sync / 1[56]:[^:]*:Parhelion:65B2:/
2047.5 "Crystallize" sync / 1[56]:[^:]*:Hydaelyn:6ED5:/ 
2055.6 "Subparhelion" sync / 1[56]:[^:]*:Hydaelyn:6C56:/
2057.6 "Crystalline Water III" sync / 1[56]:[^:]*:Hydaelyn:65A2:/
2057.8 "Beacon 1" #sync / 1[56]:[^:]*:Parhelion:65B3:/
2058.7 "--sync--" sync / 1[56]:[^:]*:Hydaelyn:65A1:/
2059.4 "Beacon 2" #sync / 1[56]:[^:]*:Parhelion:65B3:/
2061.0 "Beacon 3" #sync / 1[56]:[^:]*:Parhelion:65B3:/
2065.8 "Aureole/Lateral Aureole" sync / 1[56]:[^:]*:Hydaelyn:(6F11|65C5):/
2074.9 "Equinox" sync / 1[56]:[^:]*:Hydaelyn:65C3:/
2082.1 "--top-middle--" sync / 1[56]:[^:]*:Hydaelyn:65A9:/
2088.6 "Radiant Halo" sync / 1[56]:[^:]*:Hydaelyn:65B4:/
```

**Comment by Akurosia** [comment]
Yes it does, forgot to post the issue (or trying to fix it) but the crystalize > chakrams > aureole is not correct with the corrent version

**Comment by quisquous** [comment]
Whoops, sorry.  Fixed in #3847.  Thanks for the bug reports.

**Pull request merged**
