### PR TITLE
fisher: hotfix when Name Display Type is abbreviated, English

### PR DESCRIPTION
**Pull request by Omegakenshin**
A Hotfix for Issue #400 ,

The Fisher Overlay doesn't work if Name Display Type is not Full Name.

I tried my best, however maybe you can do it better. 
PS: Love your works, thanks.

### CODE REVIEW

**Comment by quisquous** [comment]
Thanks for this hotfix, sorry for the delay in getting back to this.  There's a few corner cases here that I need to go test in game, and then I'll merge this.

I never knew about this log name option before!

**Comment by KattTails** [comment]
With these changes, the catch regex would match every time anyone near you lands a fish?

**Comment by Omegakenshin** [comment]
> 
> 
> With these changes, the catch regex would match every time anyone near you lands a fish?

I will try to test this, however I think you might be right, but getting to a way for this to work on every name display type could need a different approach then. I'll try to check it out soon.

**Comment by KattTails** [comment]
It should work as-is with your changes so long as the FFXIV plugin parse filter is set to alliance or stricter, AND you aren't fishing with someone else in a party within /say range.  This could be an acceptable limitation, honestly.

If you wanted to solve this 'properly', you can get the player name from cactbot with e.detail.name in the eventlisteners (OnPlayerChange?), but you would need to rewrite the entire regex handling because you can't use variables in the current implementation.

**Comment by KattTails** [comment]
I did some more testing and my assumption is actually **wrong**. The parse plugin has different logs for different sources, It seems like other peoples catches are logged with a 00|2043|| prefix, whereas your own have 00|0843||. This makes everything I assumed above not matter at all, and your changes should work fine.

Sorry for the confusion..

**Comment by quisquous** [comment]
Thanks for the extra info about other fishers, that was my biggest worry that I wanted to test.

My other concern is that I think names with apostrophes won't be matched here.  (Although this is certainly better than what was there before.)

**Comment by quisquous** [comment]
Thanks for this! I'll follow up and fix apostrophes.

**Pull request merged**
