### PR TITLE
raidboss: wol and wol-ex Fr 

### PR DESCRIPTION
**Pull request by VanSlanzar**
adds missing translations and corrections Fr

### CODE REVIEW

**Comment by quisquous** [comment]
Is this ready to be merged? Did you mean to leave this as a draft request?

**Comment by VanSlanzar** [comment]
it's not finish.

**Comment by quisquous** [comment]
Are there more questions here or in #2218, or is this good to be merged?

**Comment by VanSlanzar** [comment]
there is no prob with the ablitées suddenly in the issue ?

**Comment by VanSlanzar** [comment]
Sorry, I haven't had much time lately. I understood what you wanted to do in watched the fight.
Sorry for the inconvenience.

**Comment by quisquous** [comment]
No need for apologies!!  Thanks for all the translations, and sorry for the confusion.

Is this ready to be merged?

**Comment by VanSlanzar** [comment]
`Imbued` being just an invocation for an element. You have merged that as a skill.
Imbued = Magilame in fr. You can to merge.

**Pull request merged**
