### PR TITLE
fix #1235

### LINKED ISSUE #1235: Radar. Provoke makes you the puller.
Provoke doesn't work on S Rank hunts, yet if someone uses provoke before the pull, you will see their name as puller instead of the one who actually pulls it later.

### PR DESCRIPTION
**Pull request by Bluefissure**
<del>Haven't tested it yet lol.</del>
Good for me.
Actually all hunt mobs won't be affected by provoke I think?

### CODE REVIEW

**Comment by quisquous** [comment]
Thanks!  Give it a test and let me know how it works.  😉

**Comment by Bluefissure** [comment]
> Thanks! Give it a test and let me know how it works. 😉

I tested in CN server and it worked well.

**Comment by quisquous** [comment]
Thanks for giving it a test!

**Comment by quisquous** [comment]
Actually wait, regarding your previous comment, is it the case that you can't provoke A or B ranks too? Or is it just S?

**Comment by Bluefissure** [comment]
I tested again for two B rank mobs, and both have the "(fully resisted)" on provoke, like

**Comment by Bluefissure** [comment]
However, if you're close enough you'll start auto-attacking the hunt mobs after provoking, which will make you the puller.
Anyway, we can filter the provoke out and match the attack logs.

**Pull request merged**
