### PR TITLE
raidboss: More ex6 triggers

### PR DESCRIPTION
**Pull request by valarnin**
Fix 2nd Terrastorm trigger
Add Gale Sphere triggers
Add Arctic Assault trigger
Add Flames of Eventide trigger

Not 100% sure on the arctic assault trigger yet, I was only able to find a few variations to test against.

This includes both triggers for Gale Sphere that we discussed, open to further suggestions on these. Example screenshot from raidemulator for each of the new triggers:

image
image

### CODE REVIEW

**Comment by valarnin** [comment]
There are some issues with these in-instance. Trying to sort them out still.

**Comment by wexxlee** [comment]
> This includes both triggers for Gale Sphere that we discussed, open to further suggestions on these.

It might be helpful to call the clone order a little before calling the safe spots so you don't get stacked info alerts.  You can determine the order the clones will fire based on the Goldez's Shadow combatants.  They each use a different ability indicating which wall they will float to.  IIRC:

844F: North
8450: East
8451: West
8452: South

**Comment by quisquous** [comment]
> There are some issues with these in-instance. Trying to sort them out still.

Yeah, the clone order was correct for me but it felt like E/W N/S directions were (always?) swapped during gale sphere.  N/S seemed ok for the meteors + ice spikes but E/W also was (always?) backwards.

**Comment by valarnin** [comment]
This should be ready for a proper review now.

**Comment by Perplexity** [comment]
Gale Sphere safespots are wrong sometimes.

**Comment by valarnin** [comment]
> Gale Sphere safespots are wrong sometimes.

With the latest version? 6ff8031 or 744567d.

**Comment by Perplexity** [comment]
> > Gale Sphere safespots are wrong sometimes.
> 
> With the latest version? [6ff8031](https://github.com/quisquous/cactbot/commit/6ff8031f7501ee4cbc3ebed0248709576a055b23) or [744567d](https://github.com/quisquous/cactbot/commit/744567d84476ec3c4d1637c22ab39af6dbd4bc64).

Will try actually

**Comment by Perplexity** [comment]
Okay it works with the newer commits, my bad. Good stuff

**Comment by Perplexity** [comment]
Terraform 2 safe spots are wrong, it seems to always be the opposite?

**Comment by valarnin** [comment]
> Terraform 2 safe spots are wrong, it seems to always be the opposite?

The ice spike wall is inverted sometimes during terra 2 I think. I'm investigating that.

**Pull request closed without merging**
