### PR TITLE
util: fix when the log time is 00

### PR DESCRIPTION
**Pull request by tssailzz8**

### CODE REVIEW

**Comment by quisquous** [comment]
Could you describe the bug that you're fixing here a little bit more? I'm not sure I understand the situation.

**Comment by tssailzz8** [comment]
When the battle time is in 00 o'clock, it will be converted to “24:” but the log time is ”00:”

**Comment by valarnin** [comment]
Huh, that's a fun node bug. Has it been reported upstream?

image

**Comment by quisquous** [comment]
Ah, good find, valarnin!  Sorry for not looking at this PR earlier.  I've been busy with ultimate and wanted to look if there was a better way to do this, but valarnin beat me to it.  Can we use that instead?

**Pull request closed without merging**
