### PR TITLE
jobs: always show pull bar

### PR DESCRIPTION
**Pull request by Jaehyuk-Lee**
I wanted pull bar on because I should use Battle Litany on 5 seconds before battle starts (on e8s), but there were no separate option for pull bar. Just Party Buffs option turned off pull bar.

### CODE REVIEW

**Comment by quisquous** [comment]
Do you think we should always show the pull bar, vs having an option?

**Comment by Jaehyuk-Lee** [comment]
I would like to have always show the pull bar, since it's shown before combat. It doesn't disturb you.

**Comment by quisquous** [comment]
I'm supportive of that.  I agree it doesn't really get in the way, so maybe it's better to just always show it rather than have an option.

**Comment by quisquous** [comment]
Thanks!

**Comment by quisquous** [comment]
If folks really don't want the pull bar, they can add CSS.

**Pull request merged**
