### PR TITLE
O7S Timeline fix

### LINKED ISSUE #44: O7S Timeline Sync Paste Ultros / Ink
428 "Paste Ultros" sync /:Guardian:2776:/
429 "Ink" sync /:Guardian:277D:/

I'm not sure whats up but it ever so slightly desyncs around this part. I was seeing the timer with 10 seconds left, but ink would go off. This is post Virus phase.

It would pick up and sync up again later, but heres the skill IDs fro the log:

[21:51:06.219] 14:2776:Guardian starts using Paste Program on Guardian.
[21:51:11.000] 00:282b:The Guardian uses Paste Program.

I think just adjusting the duration here to be 5 seconds instead of 10 will fix it, if possible.

### PR DESCRIPTION
**Pull request by xephero**
Adjusted the flight windows to all match the right timing windows, and adjusted all the other lines afterward to maintain the same differences. Should resolve #44

### CODE REVIEW

**Comment by zirwin** [comment]
Was able to test this tonight. I had a +2s error before virus on the ultros path, so the extra commit is to adjust those all downward that 2 seconds.

Video: https://www.twitch.tv/videos/227501060
Log: https://www.fflogs.com/reports/2d9MqcVTHYa6rLWJ#fight=22&hostility=1&type=casts&view=events

**Comment by xephero** [comment]
Whoops, wrong account. Reposting:

Was able to test this tonight. I had a +2s error before virus on the ultros path, so the extra commit is to adjust those all downward that 2 seconds.

Video: https://www.twitch.tv/videos/227501060
Log: https://www.fflogs.com/reports/2d9MqcVTHYa6rLWJ#fight=22&hostility=1&type=casts&view=events

**Comment by xephero** [comment]
Just wanted to mention here: ran O7S tonight with four enrages(!) and there weren't any desyncs that I noticed.

Video: https://www.twitch.tv/videos/227822401
Log: https://www.fflogs.com/reports/qypNc3A7LW9B8DhV

**Comment by quisquous** [comment]
Congrats on the clear!  Sorry you had to do so much testing, but glad to hear it's looking good.  :)

**Pull request merged**
