### PR TITLE
2.X&3.X CN triggers

### PR DESCRIPTION
**Pull request by ShadyWhite**

### CODE REVIEW

**Comment by ShadyWhite** [comment]
ahhh，I don't know why the build was failed.

**Comment by Akurosia** [comment]
for t8 line 97 you have a " ' "  to much at the end of the variable
t9 line 121: there is a space before the comma(at the end of the line) which needs to be removed
dun_scaith line 169: remove the empty line
shatter line 41: closing bracket has 2 spaces to much (allign it with the cn)

**Comment by ShadyWhite** [comment]
> for t8 line 97 you have a " ' " to much at the end of the variable
> t9 line 121: there is a space before the comma(at the end of the line) which needs to be removed
> dun_scaith line 169: remove the empty line
> shatter line 41: closing bracket has 2 spaces to much (allign it with the cn)

Thanks very much,all fixed.

**Comment by quisquous** [comment]
Thanks! If you didn't know, you can run `npm run lintfix` and `npm run test` locally to see the same errors that the bot would give you.  https://github.com/quisquous/cactbot/blob/master/CONTRIBUTING.md#build-problems also tries to explain the process to get to the build error page where you can see the errors that Akurosia listed.

**Comment by VanSlanzar** [comment]
https://github.com/quisquous/cactbot/pull/1288

If you don't know how to do it, I invite you to read it all on this post. @quisquous  helped me a lot to install and understand how to do it locally.

**Pull request merged**
