### PR TITLE
raidboss: add knockback notice in shiva unreal

### PR DESCRIPTION
**Pull request by MaikoTan**
So players can use anti-knockback skills
(save poor BLM `(*/ω＼*)` )

### CODE REVIEW

**Comment by quisquous** [comment]
Hmm.  I'm not sure about this recommendation, because if you use your knockback here, you won't have it up if you get picked for the avalanche laser.  This knockback is also prevented if there's any sort of shield.  Maybe it'd be better to tell paladins and healers to shield for the knockback?

**Comment by MaikoTan** [comment]
Well, maybe that is the difference that we solve the mechanic?
We always use surecast at `Heavenly Strike`,
then come to `Avalanche`, MT would pull Shiva to the north edge, the chosen one stand at back of shiva and wait for knockback, others should stand in front or at the side of shiva to avoid that knockback laser.

**Comment by MaikoTan** [comment]
Or we can make it as an `info`, not a default `alert` so user can determine how their surecast uses?

**Comment by quisquous** [comment]
Yeah, info sounds good to me.  I can add a separate "shield" trigger for paladins and healers too.

(FWIW, we also pull Shiva to the edge, but then you still got knocked back if you get picked if you don't surecast.)

**Pull request merged**
