### PR TITLE
raidboss: adjust p10s bonds timing, message severity

### PR DESCRIPTION
**Pull request by quisquous**
Some of the bonds messages (especially bonds1 and bonds4) could use a much earlier warning, so add a custom delay/duration for each of the four different bonds mechanics.

There's also a lot of info that lines up with bonds warnings so bump some priorities around so there's less info overload.

### CODE REVIEW

**Comment by Legends0** [comment]
I'm not sure if it's just me but this change makes it more difficult to discern what it's trying to say when this happens (which occurs first):
image

**Comment by quisquous** [comment]
That looks like an error to me.  It should say `Spread => Partners`, then `Partners`.

**Comment by quisquous** [comment]
Yeah ok, there's definitely some bugs here.  Let me see if I can fix them or if I should revert.

**Comment by quisquous** [comment]
Put up #5572

**Pull request merged**
