### PR TITLE
resources: switch audio container from `.ogg` to `.webm`

### PR DESCRIPTION
**Pull request by marzent**
According to https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers:
>While Ogg has been around for a long time, it has never gained the wide support needed to make it a good first choice for a media container. You are typically better off using WebM

Right now WebKit-based browsers will only playback Vorbis encoded audio inside a `.webm` container. Conversion was done with `find . -type f -iname "*.ogg" -exec bash -c 'FILE="$1"; ffmpeg -i "${FILE}" -c:a copy -vn -y "${FILE%.ogg}.webm";' _ '{}' \;` without re-encoding, preserving the original audio stream.

### CODE REVIEW

**Comment by quisquous** [comment]
Unfortunately, this does not appear to work on Windows in OverlayPlugin or in Chrome M94 via websockets for me.  I get a `DOMException: Failed to load because no supported source was found.` on every `void audio.play` from `_playAudioFile` in `popup-text.ts`.  Do you have any suggestions?

```diff
diff --git a/ui/raidboss/popup-text.ts b/ui/raidboss/popup-text.ts
index 686398167..45051140d 100644
--- a/ui/raidboss/popup-text.ts
+++ b/ui/raidboss/popup-text.ts
@@ -1378,7 +1378,10 @@ export class PopupText {
   _playAudioFile(triggerHelper: TriggerHelper, url: string, volume?: number): v
oid {
     const audio = new Audio(url);
     audio.volume = volume ?? 1;
-    void audio.play();
+    audio.play().catch((e) => {
+      console.log(e);
+      onTriggerException(triggerHelper.trigger, e);
+    });
   }

   getDataObject(): RaidbossData {

```

**Comment by marzent** [comment]
Hm locally this runs fine on Mac and Windows on Chromium, Firefox and Safari

**Comment by marzent** [comment]
I think `git` might have bricked my files...

```
warning: LF will be replaced by CRLF in resources/sounds/BigWigs/Alarm.webm.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in resources/sounds/BigWigs/Alert.webm.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in resources/sounds/BigWigs/Info.webm.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in resources/sounds/BigWigs/Long.webm.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in resources/sounds/Overwatch/D.Va_-_Boosters_engaged.webm.
```
etc...

**Comment by marzent** [comment]
Should be fixed now

**Pull request merged**
