### PR TITLE
Raidboss: TEA head marker fix

### LINKED ISSUE #1199: Cactbot Limit Cut/Enumeration not working
With the latest ffxiv plugin, cactbot callout for Enumeration and Limit Cut is not working in TEA...

I'm not sure what would be the fix, have tried reloading overlay and plugin...

### PR DESCRIPTION
**Pull request by JLGarber**
This turned out to be significantly simpler than I expected after Quisquous pointed me in the right directions. Note that it is entirely untested as I wasn't able to get the raid emulator working over lunch. However, looking things over there's no reason it shouldn't work. 

Apologies for the ugly bits. I mostly wanted to get concepts set down so we could improve on them and get this out for people as quickly as possible.

(Should resolve #1199 )

### CODE REVIEW

**Comment by quisquous** [comment]
I think this looks good.  Was there anything else you wanted to change before merging? Just ask because it's still marked as a draft.

**Comment by quisquous** [comment]
And, I think the raid emulator can be pretty tetchy about TEA logs too.  They tend to be bigger than fit in local storage unless they're clipped to somewhere in the inception phase.  This is one reason why I want to move raid emulator to use indexeddb instead of local storage (#853).

**Comment by JLGarber** [comment]
Oh, if there's nothing else to review, then it's ready.

**Comment by Legends0** [comment]
I tried this out in the raid tonight... seems all numbers but the first will get a callout. If the player with cactbot gets the one on the first limit cut, cactbot doesn't make a callout for them.

**Comment by JLGarber** [comment]
Interesting. Glad to know that it's mostly working. I don't have any way of testing it myself, so I'm relying on reports like this. I'll open an issue based on this report so we don't clutter this pull request and we can work things out from there?

**Pull request merged**
