### PR TITLE
Resources:CN 5.3 zone_info

### PR DESCRIPTION
**Pull request by ShadyWhite**

### CODE REVIEW

**Comment by Akurosia** [comment]
fyi: dont forget to update fish data :)

**Comment by ShadyWhite** [comment]
> fyi: dont forget to update fish data :)

Waiting for @Bluefissure to update fish data and FFXIVProcessCn.cs.

**Comment by Akurosia** [comment]
just run the gen_fisher_data.py in the util folder o.o or am i missing something else?

**Comment by ShadyWhite** [comment]
> just run the gen_fisher_data.py in the util folder o.o or am i missing something else?

Just because I don't have the Int client on my PC,LOL.

**Comment by Bluefissure** [comment]
Got ear infection and need to go to hospital today.
Will do tonight if still in-need.

**Comment by quisquous** [comment]
Please take care! I ran the fisher script myself locally and updated it in 5563dd7361.

**Pull request merged**
