### PR TITLE
O5S Timeline syncs

### PR DESCRIPTION
**Pull request by xephero**
More complete version of O5S, still untested until tomorrow's reset. From #37

### CODE REVIEW

**Comment by quisquous** [comment]
I'll give this a run tomorrow night too and then merge after that if it looks good.

Thanks a bunch! Appreciate the separate pull requests too.  It makes it a lot easier to work with.

**Comment by xephero** [comment]
Just tested it, and it reset. The console has OnSync messages up to 203 (the Diabolic Wind in add phase), and after that no syncs happened. I'm not sure if it should print a message if the jump 0 errantly came up at any point. My log doesn't have any "Removing combatant Phantom Train" until the end though.

**Comment by xDemonessx** [comment]
Same just happened to me, the timeline halted during midphase when ghosts were out.

**Comment by xephero** [comment]
Added gigantic sync windows for the abilities that the boss only uses once in the whole fight. If it does end up stopping for some reason, it should resync once it sees those.

**Comment by quisquous** [comment]
I think there's still some bugs to fix here, but this is an improvement over what was there before.

**Comment by xephero** [comment]
I've been making these for myself and my statics since Gordias, I'm just happy to have a channel to get them out there more effectively. Thanks for your work!

**Pull request merged**
