### PR TITLE
i18n: add missing transaltions - Misc test fr

### PR DESCRIPTION
**Pull request by VanSlanzar**
@quisquous or @Akurosia

For these 3 regex, I'm not sure. Is there a way to check them?
```
netRegexFr: NetRegexes.echo({ line: 'cactbot langue.*?', capture: false }),
netRegexFr: NetRegexes.echo({ line: 'cactbot test de réponse.*?', capture: false }),
netRegexFr: NetRegexes.echo({ line: 'cactbot montre d\'essai.*?', capture: false }),
```

### CODE REVIEW

**Comment by quisquous** [comment]
Hmm.  I'm not sure what you're asking.  These are just commands in game, e.g. `/echo cactbot langue`.

That said, I'm not sure that these *should* have translations? I think these are just debugging commands to test things out, and so probably they should be the same in all languages.  What do you think, @Akurosia?

**Comment by Akurosia** [comment]
i would be fine in either scenario,
Best thing would be if both the english and the translated commnd would work^^'
But i think with the current implementation just english would be the best to avoid confusion (but tbh most users will never use any of these commands)

**Comment by VanSlanzar** [comment]
You can merged. I understood what the regex wanted to do. It's OK.

**Comment by VanSlanzar** [comment]
Thank you for your respons. That helped me.

**Pull request merged**
