### PR TITLE
i18n: add palace timeline translations

### PR DESCRIPTION
**Pull request by Akurosia**

### CODE REVIEW

**Comment by mooondark** [comment]
@Akurosia , I wonder why the 1st letter in not in capîtal in FR. Is there something in the script you use or maybe the source is wrong.

Is it possible to change this ?
Moon.

**Comment by Akurosia** [comment]
this is how i extract it from saint coinach. As i am not familiar what and when to capitalize a word in french, there would be no way i can make changes that would propperly fit.

**Comment by mooondark** [comment]
It's very easy, only the 1st letter of the sentence should be in capital.

**Comment by quisquous** [comment]
For what it's worth, the `replaceSync` sections are not not case sensitive and are not seen by players.  So, in some senses it shouldn't matter what the capitalization is.

**Pull request merged**
