### PR TITLE
raidboss: TOP add missing replaceSync

### PR DESCRIPTION
**Pull request by Souma-Sumire**

### CODE REVIEW

**Comment by quisquous** [comment]
Are these all of the missing translations? It looks like `missingTranslations: true` is still set.

**Comment by Souma-Sumire** [comment]
I'm not sure, but it appears that way.

Additional question: So should we remove missingTranslations when it's complete?
(I was unaware of the purpose of this property, as it only exists in the ja and fr branches in the main branch, and it doesn't exist in the cn and de branches. I don't understand the other languages, so I can't discern their differences.)

**Comment by quisquous** [comment]
Yes, definitely, remove it if unneeded.

If you run `npm run util -- findTranslations -f . -l fr` (or `-l ja` etc etc) it will show you all the missing translations for that language, including files where `missingTranslations` is set to true when not needed.

**Comment by Souma-Sumire** [comment]
Thank you for the tutorial. After running the command, I see a lot of unresolved issues, and I believe this is a massive project that lacks long-term maintenance.

**Comment by quisquous** [comment]
I think there's a number of issues, for sure. I think visibility (as probably only a few people know that command at this point, and so don't understand which translations are missing) is definitely part of it. I'll look into adding the missing translations as part of the build process (maybe the coverage generator??) and so it will be much more obvious which fights are missing translations and where.

**Comment by quisquous** [comment]
https://github.com/quisquous/cactbot/pull/5657 should address some of this. I'll add to my list to write some better documentation for translators as well.

**Pull request merged**
