### PR TITLE
Knockback and Cleave callouts for Limit Cut in TEA

### PR DESCRIPTION
**Pull request by Legends0**
delaySeconds calculated from duration from when player first gets their marker to when the charge or cleave for that player goes off - 5 seconds.

Does not necessarily mean that that player is the one getting hit... if they died then some other player will just be charged or cleaved.

Cleave on you callout is used... cleave behavior is slightly different from tank cleave as you must face away from the part versus tank cleave facing towards.

### CODE REVIEW

**Comment by Legends0** [comment]
Comment should probably be updated to something, I took the comment from e3s, but this trigger includes cleave callout.

**Comment by Legends0** [comment]
This does not work yet, need to convert string to hex to do binary comparison properly.

**Comment by Legends0** [comment]
The timings don't work for the second limit cut.

**Comment by quisquous** [comment]
Thanks! I got a log and a video through the end of the fight, so I'll see what this looks like and fix it up for wormhole if it's not good.

**Comment by quisquous** [comment]
I really appreciate all the ultimate triggers and timelines! :+1: :+1: :+1:

**Pull request merged**
