### PR TITLE
lint: apply sort-keys to .eslintrc.cjs

### PR DESCRIPTION
**Pull request by quisquous**
I am not sure what I think about this.  I feel like the eslint file is getting really big and things are added all over the place.  Forcing the keys to be sorted keeps it in a more reasonable order, but also makes it slightly less readable?  I am not sure.

### CODE REVIEW

**Comment by valarnin** [comment]
It might make more sense to have top-level keys be unsorted, but subkeys be sorted?

**Comment by quisquous** [comment]
Is there a way to convince the eslint rule to do that?

**Comment by valarnin** [comment]
Hmm, doesn't look like it with the default implementation, we'd need to extend it or something.

**Comment by quisquous** [comment]
I don't think the top-level rule ordering is *that* bad? It was kind of nice to have the larger rules/overrides entries at the bottom, but I don't know that there's really an expected order there either.

**Comment by MaikoTan** [comment]
Since it is a `JS` file, what about splitting some large sub-objects into some separated variables?

**Comment by valarnin** [comment]
> 
> 
> Since it is a `JS` file, what about splitting some large sub-objects into some separated variables?

Exactly what I was about to suggest, I think maybe the overrides section would benefit from, e.g., having `const tsOverrides = ...;` as its own object then pulled into the export?

**Comment by quisquous** [comment]
Separated variables make this a million times better, thanks!

**Pull request merged**
