### PR TITLE
Util: Function shuffling for timeline utilities.

### PR DESCRIPTION
**Pull request by JLGarber**
As I noted in #749 , there's some shuffling that should happen before I do further updates to `translate_fight`. The updates in here should be mostly self-explanatory. I'll gladly take criticism on naming or additional functionality that should be turned into helpers in addition to what I already moved.

### CODE REVIEW

**Comment by quisquous** [comment]
(Sorry, I'm out of town for a few days, but will try to review this next week when I have more time.)

**Comment by quisquous** [comment]
I did not mean to close this!

**Comment by quisquous** [comment]
This all looks great! Sorry for the delay.

**Comment by JLGarber** [comment]
Not a problem. Hope your vacation was good!

**Pull request merged**
