### PR TITLE
add effect id for Sheltron of PLD

### PR DESCRIPTION
**Pull request by Trim21**

### CODE REVIEW

**Comment by Echoring** [comment]
This file is auto-generated from `gen_effect_id.py`.
Don't edit this file directly.
You'd better add it in `known_mapping` in `util/gen_effect_id.py`.

**Comment by Trim21** [comment]
Thanks

**Comment by Echoring** [comment]
Oh, remember to change this Hex ID it to decimalism in that py file.

**Comment by MaikoTan** [comment]
And you could just force push (force-update) to this PR branch, not neccesary to close it and open a new one.

**Comment by Trim21** [comment]
I forgot...

**Pull request closed without merging**
