### PR TITLE
raidboss: TOP add config option + rotation to omega dodge

### PR DESCRIPTION
**Pull request by quisquous**
Because the rotation direction depends on which side you have dodged to, it's impossible to write this PR without having the user pick which dodge they are doing.

This promotes the dodge direction to a new option (defaulting to far, since that seems to be the PF approach) and adds in the rotation direction as well.

Because there's an option, there's no longer any combo output strings for staff sword, and the correct one is picked.

### CODE REVIEW

**Comment by quisquous** [comment]
cc @Legends0 if you wanted to test this out too

**Comment by Legends0** [comment]
> cc @Legends0 if you wanted to test this out too

I'll try this out next time my group runs.

**Comment by Legends0** [comment]
I had it call left then far E, but that was actually right. Using far dodge.

**Comment by Legends0** [comment]
After resetting my config, it seems to have resolve itself as I haven't been able to replicate the issue.

**Comment by Legends0** [comment]
This works well since the 5372 fix. Haven't had an issue with it.

**Comment by quisquous** [comment]
Ok, I think I'll land this and do a release.  Thanks for all the testing.

**Pull request merged**
