### PR TITLE
resources: rename field in MapEffect line

### PR DESCRIPTION
**Pull request by quisquous**
Mentioned by @valarnin:
https://github.com/quisquous/cactbot/pull/4905#discussion_r985769682

### CODE REVIEW

**Comment by quisquous** [comment]
also @wexxlee just FYI

**Comment by wexxlee** [comment]
> also @wexxlee just FYI

100% agree with @valarnin that it's a bitmask.  My only thought with labeling it as 'id', rather than by its datatype, was that it's functionally the field that identifies which effect is rendered, and 'id' is a label used for similar purposes in other log lines (thinking specifically of NetworkTargetIcon).  But either way is fine with me - I'll update #4907 if/once this is merged.

**Comment by wexxlee** [comment]
Oh, and if the field name does change, there probably should also be an update to the log guide, as the field is mentioned in the description text.

**Comment by quisquous** [comment]
> Oh, and if the field name does change, there probably should also be an update to the log guide, as the field is mentioned in the description text.

Oh, thanks.  I forgot about that.  `*<_<*`

**Pull request merged**
