### PR TITLE
Revert "refactor(resources): migrate WidgetList to TypeScript"

### PR DESCRIPTION
**Pull request by quisquous**
Reverts quisquous/cactbot#2532

@Trim21 I'm sorry to revert this, but this patch was causing all of my overlays to run with extreme lag.  Normally I wouldn't revert and would just fix, but I think this is a pretty bad bug.  My jobs overlay would print `BrowserConsole: Element with id child20 is missing? (Source: http://localhost:8080/dist/jobs.bundle.js, Line: 10214)` many times a second.  When I reverted this patch locally it stopped happening, so I feel pretty confident that this is the issue.

### CODE REVIEW

**Comment by Trim21** [comment]
Looks like there is some bug in `removeElement`， I'll try to fix it

**Comment by Trim21** [comment]
look like I'll get a notification every this commit is pushed to a fork...

**Comment by MaikoTan** [comment]
Click unsubscribe button?

**Comment by Trim21** [comment]
> Click unsubscribe button?

Then I just unsubscribed from this commit in this forked repo.

**Pull request merged**
