### PR TITLE
plugin: support for type rename in FFXIV_ACT_Plugin 2.6.2.0

### PR DESCRIPTION
**Pull request by KattTails**
Thanks to @ngld for most of these fixes.

Sorry for the headaches, let me know if there's any way to improve this.

### CODE REVIEW

**Comment by KattTails** [comment]
Oh, I just saw #3731. Not sure what the best way forward is now that this conflicts, let me know if I need to do anything to fix this!

**Comment by quisquous** [comment]
> Oh, I just saw #3731. Not sure what the best way forward is now that this conflicts, let me know if I need to do anything to fix this!

Sorry, I just wanted a quick fix to get something out.  Feel free to just take your changes over that one.

**Comment by KattTails** [comment]
Think I got it? It's actually the first time I've resolved conflicts in github so please double check I didn't screw it up..

**Comment by ngld** [comment]
Looks good to me. Should fix the issue and it won't break the KR and CN versions. 👍

**Pull request merged**
