### PR TITLE
raidboss: Add Option to Order Timeline Bottom-to-Top

### PR DESCRIPTION
**Pull request by panicstevenson**

### CODE REVIEW

**Comment by panicstevenson** [comment]
Small demo gif:
Demo

**Comment by panicstevenson** [comment]
Converting to draft since there's a small bug with KeepExpiredTimerBarsForSeconds not being honored if the timerbar is pushed out of the window.

**Comment by panicstevenson** [comment]
To expand upon the above: I believe the bug is instead the fact that keepAlive bars are not actually a part of the grid. I think there needs to be a small refactor to make that work more in line with expectations before landing anything here.

**Comment by quisquous** [comment]
> To expand upon the above: I believe the bug is instead the fact that keepAlive bars are not actually a part of the grid. I think there needs to be a small refactor to make that work more in line with expectations before landing anything here.

I ended up doing this refactoring in #5869.

**Comment by panicstevenson** [comment]
To the two daredevils that eagerly upthumb'd the original post, your nearly 14-month wait is almost over.

**Pull request closed without merging**
