### PR TITLE
raidboss: cn eden

### PR DESCRIPTION
**Pull request by Bluefissure**
I'll test tomorrow and check whether there are any problems.

### CODE REVIEW

**Comment by quisquous** [comment]
I assume also the memory offsets need to be adjusted to use the 5.1 versions?

**Comment by Bluefissure** [comment]
> I assume also the memory offsets need to be adjusted to use the 5.1 versions?

It's patch 5.05 and the offsets remain the same as 5.01.

**Comment by KattTails** [comment]
cn client is on v5.05 according to [this](http://ff.sdo.com/web8/index.html#/patchnote).

**Comment by quisquous** [comment]
Is this still a work in progress? Is this ready to be merged?

**Comment by Bluefissure** [comment]
> Is this still a work in progress? Is this ready to be merged?

Yes, you can merge it now. O(∩_∩)O~

**Pull request merged**
