### PR TITLE
build: update vscode settings/extensions for pylint

### PR DESCRIPTION
**Pull request by quisquous**

### CODE REVIEW

**Comment by sleepylinde** [comment]
adding this commit to my fork made vscode throw a different error. I opened vscode without having done `npm start`  beforehand:

> 2023-11-06 07:01:42.519 [info] [Info  - 7:01:42 AM] (15584) Pylance language server 2023.11.10 (pyright 088ebaa5) starting
2023-11-06 07:01:42.519 [info] [Info  - 7:01:42 AM] (15584) Server root directory: C:\Users\user\.vscode\extensions\ms-python.vscode-pylance-2023.11.10\dist
2023-11-06 07:01:42.519 [info] [Info  - 7:01:42 AM] (15584) Starting service instance "cactbot"
2023-11-06 07:01:42.545 [info] [Info  - 7:01:42 AM] (15584) Setting pythonPath for service "cactbot": "C:\Python312\python.exe"
2023-11-06 07:01:42.545 [info] [Info  - 7:01:42 AM] (15584) Setting environmentName for service "cactbot": "3.12.0 (global)"
2023-11-06 07:01:42.602 [info] [Info  - 7:01:42 AM] (15584) Assuming Python version 3.12
2023-11-06 07:01:42.743 [info] [Info  - 7:01:42 AM] (15584) Found 6 source files
2023-11-06 07:01:43.067 [info] ERROR: The process "15860" not found.

> 2023-11-06 07:01:55.125 [info] [Error - 7:01:55 AM] Server process exited with code 1.
> 2023-11-06 07:01:55.125 [info] [Error - 7:01:55 AM] Connection to server got closed. Server will not be restarted.
> 2023-11-06 07:01:55.126 [info] [Error - 7:01:55 AM] Handling connection close failed
> 2023-11-06 07:01:55.126 [info] TypeError: e.clear is not a function
> 	at _.cleanUp (c:\Users\user\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2412859)
> 	at _.handleConnectionClosed (c:\Users\user\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2417283)
> 	at _.handleConnectionClosed (c:\Users\user\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2578252)
> 	at c:\Users\user\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2416709
> 	at o.invoke (c:\Users\user\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2363387)
> 	at s.fire (c:\Users\user\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2364152)
> 	at te (c:\Users\user\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2349784)
> 	at o.invoke (c:\Users\user\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2363387)
> 	at s.fire (c:\Users\user\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2364152)
> 	at d.fireClose (c:\Users\user\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2372012)
> 	at ChildProcess.<anonymous> (c:\Users\user\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2384364)
> 	at ChildProcess.emit (node:events:525:35)
> 	at maybeClose (node:internal/child_process:1091:16)
> 	at ChildProcess._handle.onexit (node:internal/child_process:302:5)

After closing vscode, running `npm start` in the cactbot folder I got just this (and the other info logs):

> 2023-11-06 07:12:42.672 [info] ERROR: The process "15728" not found.

So I'm assuming I'm missing something but it's not breaking anything?

**Comment by quisquous** [comment]
For what it's worth, `npm start` should be unrelated to vscode issues.

I saw that same error above but then when I closed and reopened vscode, I didn't see it again. My thought was that it was some first time error? I also get `2023-11-05 23:14:51.565 [info] ERROR: The process "25860" not found.` but I don't know what it is about.

At least re: cactbot, I don't think either of these are worrisome errors. If you edit a Python file, e.g. `gen_hunt_data.py` and add some unnecessary indents and then save the file, it should re-format using black. If you edit `gen_hunt_data.py` and rename the first `list` to `List` or something, pylint shows some iteration-related errors. If both of those happen, that seems like "working" as far as vscode and cactbot are concerned.

**Comment by quisquous** [comment]
@sleepylinde Does the thumbs up mean things are working with this PR?

**Comment by sleepylinde** [comment]
AH sorry, I should've been more precise. It's the same for me as it is for you basically. It still gives the` |info] ERROR: The process "random number" not found` but the other errors are gone now!

**Comment by quisquous** [comment]
No worries, just wanted to make sure I understood!

**Pull request merged**
