### PR TITLE
TEA, e1s and e4s localize

### PR DESCRIPTION
**Pull request by r4ha**
<3

### CODE REVIEW

**Comment by quisquous** [comment]
Thank you for this! Could you remove the tea timelineReplace section, as #793 has all of the languages, and so I'm planning to merge that instead.

**Comment by r4ha** [comment]
Done!

**Comment by quisquous** [comment]
It looks like this is still conflicting, sorry.  Can you merge in your tea changes as well?

**Comment by r4ha** [comment]
ah I see! It should be ok now. sorry.

**Comment by quisquous** [comment]
Thanks thanks! Sorry for the conflicts!

**Pull request merged**
