### PR TITLE
resources: update Regexes for ffxiv plugin alpha changes

### PR DESCRIPTION
**Pull request by quisquous**
I ran a very long net log and the parsed version of that net through a test that verified that all regexes matched their appropriate lines, and also verified that the conversion was accurate.  In general, all of the conversion code went away other than some of the gameLog replacement code.

### CODE REVIEW

**Comment by Akurosia** [comment]
Shouldn't https://github.com/quisquous/cactbot/blob/ce548ff4b5a62e5f2c83c4a2cc8bcbc428ead70c/docs/LogGuide.md?plain=1#L12 be updated as well?

**Comment by quisquous** [comment]
> Shouldn't https://github.com/quisquous/cactbot/blob/ce548ff4b5a62e5f2c83c4a2cc8bcbc428ead70c/docs/LogGuide.md?plain=1#L12 be updated as well?

Done, thanks for catching that!

**Comment by Akurosia** [comment]
For https://github.com/quisquous/cactbot/pull/3686/files#diff-af3eb20d6c5ae8fe60c2919a9d350a5641b16e9fe862cfd61e10d79f22af183aR530

The 2 missing [?] are nased from the 2 codeblocks here
```csharp
		public string FormatCombatantMessage(uint CombatantID, uint OwnerID, string CombatantName, int JobID, int Level, uint WorldID, string WorldName, uint BNpcNameID, uint BNpcID, uint currentHp, uint maxHp, uint currentMp, uint maxMp, float PosX, float PosY, float PosZ, float Heading)
		{
			return ((FormattableString)$"{CombatantID:X4}|{CombatantName}|{JobID:X2}|{Level:X1}|{OwnerID:X4}|{WorldID:X2}|{WorldName}|{BNpcNameID}|{BNpcID}|").ToString(CultureInfo.InvariantCulture) + FormatCombatantProperties(currentHp, maxHp, currentMp, maxMp, null, PosX, PosY, PosZ, Heading);
		}
```
```csharp
		private string FormatCombatantProperties(uint? currentHp, uint? maxHp, uint? currentMp, uint? maxMp, byte? damageShield, float? posX, float? posY, float? posZ, float? heading)
		{
			return ((FormattableString)$"{currentHp}|{maxHp}|{currentMp}|{maxMp}|{damageShield}||{posX:0.00}|{posY:0.00}|{posZ:0.00}|{heading:0.00}").ToString(CultureInfo.InvariantCulture);
		}
```

Which from my understanding will always result in 0

**Comment by Akurosia** [comment]
https://github.com/quisquous/cactbot/blob/1a42ff96563255e351fda6e789801c658dcdd17f/docs/LogGuide.md?plain=1#L583
Is copying the same format as the the 03 lines for the missing fields

**Comment by Akurosia** [comment]
https://github.com/quisquous/cactbot/blob/1a42ff96563255e351fda6e789801c658dcdd17f/docs/LogGuide.md?plain=1#L657

the missing element will always be a 0 based on the code-snippit below

```csharp
		public string FormatPlayerStatsMessage(ulong LocalContentId, uint JobID, uint Str, uint Dex, uint Vit, uint Intel, uint Mnd, uint Pie, uint Attack, uint DirectHit, uint Crit, uint AttackMagicPotency, uint HealMagicPotency, uint Det, uint SkillSpeed, uint SpellSpeed, uint Tenacity)
		{
			return ((FormattableString)$"{JobID}|{Str}|{Dex}|{Vit}|{Intel}|{Mnd}|{Pie}|{Attack}|{DirectHit}|{Crit}|{AttackMagicPotency}|{HealMagicPotency}|{Det}|{SkillSpeed}|{SpellSpeed}|0|{Tenacity}|{LocalContentId:X8}").ToString(CultureInfo.InvariantCulture);
		}
```

**Comment by quisquous** [comment]
Re: missing fields.  I am planning to leave them as `[?]` and not specify that they must exactly be zero.  That way if they change in the future to mean something, everything will continue to work.

In the code snippet shared on discord, `FormatCombatantProperties` says `// TODO6.0 - remove double pipe here for currentTp/maxTp, replaced by damage shield.` which to me says that it's not implemented yet.  I'll wait until it is to add the field name.

**Pull request merged**
