### PR TITLE
raidboss: a7s fr

### PR DESCRIPTION
**Pull request by VanSlanzar**
adds missing translations fr + removal missingTransaltion.
Several lines disturbed me, so I have a question to be sure of what I translated in `replaceSync`.
Here is what I translated
```
'Frostbite': 'gelure',
'Pyretic': 'chaleur', 
'Quickthinx Allthoughts': 'Quickthinx le Cerveau',
'Shanoa': 'Chat-noir',
```
is that correct, or should be whole lines like below?
```
Quickthinx Allthoughts uses Sizzlespark
Quickthinx Allthoughts uses Zoomdoom
Quickthinx Allthoughts uses Sizzlebeam
Quickthinx Allthoughts uses Flamethrower
Shanoa readies Undying Affection
suffers the effect of Pyretic
suffers the effect of Frostbite
```

### CODE REVIEW

**Comment by quisquous** [comment]
Yeah, this is marked as `timelineNeedsFixing: true,` because this timeline is not done.  It shouldn't show up in `util/find_missing_translations.py` and I would not recommend doing translations for this timeline at this point.

**Comment by VanSlanzar** [comment]
If I understood correctly, what I wrote in replaceSync is correct?
How to resolve this ?  `fr:no translation for replaceText ''` sorry for the inconvenience.
it appears in the txt file.
```
924 ""
924 ""
924 ""
924 ""
924 ""
924 ""
924 ""
924 ""
924 ""
```

**Comment by quisquous** [comment]
`util/find_missing_translations.py -l fr` does not list anything for the a7s timeline.

Sorry, please do not do translations for the a7s timeline until some point in the future when it is rewritten.

**Comment by VanSlanzar** [comment]
Ok, I restored the replacText section, and just left the triggers additions. There is just a fix and addition of the zone name in replaceSync.

**Pull request merged**
