### PR TITLE
raidboss: Fix Non-Outputs stack Outputs

### PR DESCRIPTION
**Pull request by panicstevenson**

### CODE REVIEW

**Comment by panicstevenson** [comment]
There's more of these, but they all vary slightly across various languages.

**Comment by MaikoTan** [comment]
Yeah, maybe we should differentiate "Stack for damage share", "Stack for bait AoE" and "Stack for other things", 'cause these are different sentences in `ja` and `cn` (also `ko` I think?).

**Comment by panicstevenson** [comment]
Is that the same issue here then: https://github.com/quisquous/cactbot/pull/2903/files ? Should we revert that change?

**Comment by MaikoTan** [comment]
Well, looks like those text in #2903 are all stack for damage sharing?
I think it is OK though.

**Comment by panicstevenson** [comment]
Okay, `自分にスタック` and `自分に頭割り` are similar enough for that context? Sorry to be annoying, I just want to make sure I didn't make issues for anyone.

**Comment by MaikoTan** [comment]
Well, technically nope.
`スタック` just means "Stack", and `頭割り` means "Sharing damage".

**Pull request merged**
