### PR TITLE
raidboss : Fix Amdapor Keep Boss1 callouts

### PR DESCRIPTION
**Pull request by Aho-Senpai**

### CODE REVIEW

**Comment by Aho-Senpai** [comment]
Yeah will do, thanks. Sorting things out first ^^

**Comment by Aho-Senpai** [comment]
uhh ... confused noises ...

i'll just close this PR, make another branch and make another PR ...

**Comment by quisquous** [comment]
Haha okeydoke.  Happy to help wrangle git if there's something I can help with.  :)

**Comment by valarnin** [comment]
How I would have handled it:

```bash
# Diff the actual commit and save it to file
git diff 09686d07cc25e933165ca6be602351a2afd65a64..df8029b3b1758c220208f3e140bd71c49a726dff > ../patch.txt
# Update main to upstream main
git checkout main
git fetch upstream
git rebase upstream/main
# Reset the branch and then rebase it to line up to main
git checkout aho-ARR-Dungeons_triggers-normal
git reset --hard "<hash for the commit that was prior to the merge>"
git rebase main
# Re-apply the changes
git apply ../patch.txt
# whatever is needed to commit the changed file and push to github w/ --force
```

**Pull request closed without merging**
