### PR TITLE
Remove baseUrl definition from tsconfig

### PR DESCRIPTION
**Pull request by valarnin**
In regards to #3039.

Probably someone should review to make sure this fully forces relative paths, and should test it in an overlay to make sure it still works as expected.

### CODE REVIEW

**Comment by Trim21** [comment]
I have tested that importing like `'resources/languages'; ` didn't compile anymore without this configuration.

**Comment by Trim21** [comment]
Just find that `npm run build` is not called in pr ci...

**Comment by quisquous** [comment]
> Just find that `npm run build` is not called in pr ci...

I think `npm run tsc-no-emit` is run as a part of linting.  That's not 100% the same as `npm run build`, but it would catch errors like this.  Is that what you're concerned about?

> Considering add a [vercel](https://vercel.com/) to build front-end so we don't need to build pr locally and manually?

Sorry, I don't know what that is.  Maybe worth opening an issue and we can chat about it there?

Personally, given that you have to adjust an overlay url (in ACT or browser), pulling PRs locally and running out of my already set up cactbot folder is the most straightforward workflow for me.  Do you have a different workflow?

**Comment by Trim21** [comment]
> > Just find that `npm run build` is not called in pr ci...
> 
> I think `npm run tsc-no-emit` is run as a part of linting. That's not 100% the same as `npm run build`, but it would catch errors like this. Is that what you're concerned about?

 Sorry, didn't catch that. Look good.

**Comment by quisquous** [comment]
This seems fine to me, and a brief smoke test didn't turn anything up.

**Pull request merged**
