### PR TITLE
jobs: Convert Buff Icon Data URLs to PNG

### PR DESCRIPTION
**Pull request by panicstevenson**
Convert job-icons.js data URLs to individual buff icons in PNG format.

Closes https://github.com/quisquous/cactbot/issues/568

### CODE REVIEW

**Comment by quisquous** [comment]
Would you mind also removing the icons js file and updating jobs to use these new files?

**Comment by panicstevenson** [comment]
Done! I was trying to keep the changes as small as possible, but I guess it was probably too small to even be a functional change

**Comment by panicstevenson** [comment]
Missed one; luckily it was pretty simple to catch in testing!

**Comment by quisquous** [comment]
Thank you so much for taking care of this!

**Pull request merged**
