### PR TITLE
feat(coverage): keep table header on top

### PR DESCRIPTION
**Pull request by MaikoTan**
via adding a tricky sticky css rule.

### CODE REVIEW

**Comment by quisquous** [comment]
I like this idea a lot, but now the header is on top of the text:
image

Is there some way in CSS to make this not happen and to create some space for the sticky table header?

**Comment by MaikoTan** [comment]
Maybe we can add a background color to the headers?

**Comment by quisquous** [comment]
> Maybe we can add a background color to the headers?

Sounds reasonable to me! It could just be the white background color of the page, and then it would at least be opaque.

**Comment by MaikoTan** [comment]
image
Maybe better?

**Comment by quisquous** [comment]
Looks good to me!

**Pull request merged**
