### PR TITLE
ci: make language pr labels lowercase

### PR DESCRIPTION
**Pull request by quisquous**

### CODE REVIEW

**Comment by Trim21** [comment]
It's already in low case

**Comment by quisquous** [comment]
> It's already in low case

#2985 has uppercase, and the code says uppercase.  If you agree they should be lowercase, then I'm glad because that's what this PR is trying to do.

**Comment by Trim21** [comment]
Sorry, I mean `lang.toLowerCase()`

**Comment by quisquous** [comment]
> Sorry, I mean `lang.toLowerCase()`
> 
> lang is in low case already

OH! oops I understand now

**Pull request merged**
