### PR TITLE
raidboss: p7s add chaser baits

### PR DESCRIPTION
**Pull request by Legends0**

### CODE REVIEW

**Comment by Legends0** [comment]
Maybe Away from Bridge and/or get together would be a better phrase to say?

**Comment by panicstevenson** [comment]
This feels kind of not necessary? Maybe if we called which direction you'd be going? Unsure, but it feels like you're just dodging a floor AoE here (plus a bird)

**Comment by quisquous** [comment]
Is this already covered by #4781 ?

**Comment by Legends0** [comment]
It is a later call out., but I can agree that it can be handled by adjusting what #4781, or even the callout in the egg collection. I may this (after closing the pr) plus delay or timing of the aoe Puddle if I can get that to call out the platform to run towards.

**Pull request closed without merging**
