### PR TITLE
cactbot.dll: automatic overlay reload on file change

### PR DESCRIPTION
**Pull request by DrLippe**
I got really tired of always being in need to reload the overlay manually.
Give me your thoughts on this!

I'm impressed how many changes Visual Studio does to the files when adding a checkbox...

### CODE REVIEW

**Comment by DrLippe** [comment]
image

Works!

**Comment by quisquous** [comment]
This looks really neat, thanks!  I should be able to take a look at this later this coming weekend.

**Comment by quisquous** [comment]
This is *so* great.

**Comment by quisquous** [comment]
One followup here would be to handle user files too.

**Comment by DrLippe** [comment]
definetly! I will add this

**Pull request merged**
