### PR TITLE
raidboss: Additional ESLint Rules for ARR Triggers

### PR DESCRIPTION
**Pull request by panicstevenson**
Enable additional core ESLint rules for triggers:
- https://eslint.org/docs/rules/arrow-body-style
- https://eslint.org/docs/rules/eqeqeq
- https://eslint.org/docs/rules/no-unused-vars (with `_` as an exception)
- https://eslint.org/docs/rules/prefer-arrow-callback
- https://eslint.org/docs/rules/prefer-const

Additionally, running the following rule locally:
- https://www.npmjs.com/package/eslint-plugin-prefer-arrow

### CODE REVIEW

**Comment by quisquous** [comment]
What do you mean by `eslint-plugin-prefer-arrow` locally, vs the others?

**Comment by panicstevenson** [comment]
> What do you mean by eslint-plugin-prefer-arrow locally, vs the others?

I haven't added it to `package.json`, I didn't know the comfort level of that. So, I was holding off on committing that rule, while at the end of this I was planning on turning on the others within `package.json`.

**Comment by quisquous** [comment]
Also cc @JLGarber on this too.  I think this is all not controversial, and having eslint to make everything consistent and use more modern js practices seems like a win all around.

**Comment by JLGarber** [comment]
Yes please, more modernization.

**Pull request merged**
